artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source: https://github.com/Ankitzanzmera/data_repository/raw/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/
  
data_validation:
  root_dir: artifacts/data_validation
  data_validation_status_file: artifacts/data_validation/status.txt
  data_validation_required_file: ["valid","train","test","dataset-dict.json"]